### ISSUE TITLE
Handle world_info server message.

### ISSUE THREAD

**Issue by jkb0o** [jkb0o/rocketz-old#8]
And take world dimensions from message instead of config.

**Comment by baitcode** [comment]
There is no such message! You NERD!

**Comment by baitcode** [comment]
No everithing it's ok, the main problem is that we must implement message queue on client side to be able to create thst shit coz obj create message comes earlier than world info thus layers are not initialized yet.

**Comment by jkb0o** [comment]
There is no needs for queue yet. Organize message ordering on server is simpler.
